return {
    "folke/which-key.nvim",
    event = "VeryLazy",
    opts = {
        preset = "modern",
        delay = function(ctx) return ctx.plugin and 0 or 200 end,
        icons = {
            mappings = false,
            colors = true,
            keys = {
                C = "Ctrl ",
            },
        },
        spec = {
            { "<leader>",   group = "Leader",         },
            { "<leader>l",  group = "LSP",            },
            { "<leader>f",  group = "Find",           },
            { "<leader>g",  group = "Git",            },
            { "<leader>w",  group = "Window",         },
            { "<leader>ws", group = "Window swap",    },
            { "<leader>m",  group = "Markdown",       },
            { "<leader>r",  group = "Refactor",       },
            { "<leader>p",  group = "Print",          },
            { "<leader>t",  group = "TODO/Tab/Table", },
            { "<leader>u",  group = "UI Toggle",      },
            { "<leader>s",  group = "SOS/Sidekick",   },
            { "<leader>b",  group = "Buffer",         },
            { "<leader>q",  group = "Session",        },
            { "<leader>e",  group = "Explorer",       },
            { "<leader>h",  group = "Harpoon",        },
            { "<leader>c",  group = "Candela",        },
            { "<leader>a",  group = "Avante",         },
            { "<leader>z",  group = "Zen",            },
            { "g",          group = "Goto",           },
            { "]",          group = "Jump next",      },
            { "[",          group = "Jump previous",  },
            { "z",          group = "Folds",          },
        },
        plugins = {
            marks = true,
            registers = true,
            spelling = { enabled = true, suggestions = 20 },
            presets = {
                operators = true,
                motions = true,
                text_objects = true,
                windows = true,
                nav = true,
                z = true,
                g = true,
            },
        },
        win = {
            border = "rounded",
            wo = { winblend = 10 },
        },
        sort = { "local", "order", "group", "alphanum", "mod" },
        replace = {
            desc = {
                { "^:%s*", "" },
                { "<[cC]md>", "" },
                { "<[sS]ilent>", "" },
                { "^lua%s+", "" },
                { "<CR>", "" },
            },
        },
    },
}
